# Generated by Django 4.2.7 on 2024-09-20 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cumpleanio',
            fields=[
                ('disponible', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Fraternidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(default='', null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('mensualidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_suspendido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_no_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turno_semanal', models.CharField(default='', max_length=50)),
                ('link_whatsapp', models.URLField(blank=True, default='', max_length=700, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('banco', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('nro_cuenta', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=700)),
                ('video_id', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mostrar', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('fraternidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.fraternidad')),
            ],
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=700)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('secuencia', models.IntegerField(blank=True, default=0)),
                ('mostrar', models.BooleanField(default=False)),
                ('tag', models.CharField(default='', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('fraternidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.fraternidad')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=256)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mostrar', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('fraternidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.fraternidad')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.cronograma')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.diasemana')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.horario')),
            ],
        ),
    ]
