# Generated by Django 4.2.7 on 2025-06-02 03:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moneda', models.CharField(default='BOB', max_length=3, verbose_name='Moneda')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('unsolouso', models.BooleanField(default=True, verbose_name='Un solo uso')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de expiración')),
                ('datos', models.TextField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('cuenta_destino', models.CharField(max_length=50, verbose_name='ID Cuenta destino')),
                ('qr_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del QR')),
                ('generado', models.BooleanField(default=False, verbose_name='Generación exitosa')),
                ('api_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de la API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user_craeted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Registro de QR',
                'verbose_name_plural': 'Registros de QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
