# Generated by Django 4.2.3 on 2023-08-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraternidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=7)),
                ('direccion', models.CharField(default='', max_length=300)),
                ('mensualidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_suspendido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_no_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turno_semanal', models.CharField(default='', max_length=50)),
                ('banco', models.CharField(default='', max_length=150)),
                ('nro_cuenta', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('url', models.URLField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('fraternidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fraternidad')),
            ],
        ),
    ]
