# Generated by Django 4.2.3 on 2023-08-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraternidad',
            name='banco',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='color',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='direccion',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='nro_cuenta',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
