# Generated by Django 4.2.3 on 2023-09-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_cumpleanio_id_alter_cumpleanio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=256)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mostrar', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=700)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('secuencia', models.IntegerField(blank=True, default=0)),
                ('mostrar', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=700)),
                ('video_id', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mostrar', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='url',
            field=models.URLField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fraternidad',
            name='nro_cuenta',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Medio',
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='fraternidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fraternidad'),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='fraternidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fraternidad'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fraternidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fraternidad'),
        ),
    ]
