# Generated by Django 4.2.3 on 2023-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_notificacion_user_remitente_delete_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='url',
            field=models.URLField(max_length=700),
        ),
    ]
