# Generated by Django 4.2.7 on 2024-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_cronograma_diasemana_horario_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediavideo',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
