# Generated by Django 4.2.7 on 2024-04-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_rename_url_fraternidad_link_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraternidad',
            name='link_whatsapp',
            field=models.URLField(blank=True, default='', max_length=700, null=True),
        ),
    ]
