# Generated by Django 4.2.3 on 2023-09-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_copy_ci_useraccount_financial_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
