# Generated by Django 4.2.3 on 2023-09-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_admin_useraccount_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='financial_condition',
            field=models.CharField(choices=[('Normal', 'normal'), ('Plan de Pagos', 'plan')], default='Normal', max_length=17),
        ),
    ]
