# Generated by Django 4.2.7 on 2024-10-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_alter_agenda_options_alter_detallepagoevento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.gestion'),
        ),
    ]
