# Generated by Django 4.2.7 on 2024-10-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_alter_mensualidad_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo_evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agendas.tipoevento', verbose_name='Tipo de evento'),
        ),
    ]
