# Generated by Django 4.2.7 on 2025-06-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
