# Generated by Django 4.2.7 on 2025-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0006_alter_cupon_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
