# Generated by Django 4.2.3 on 2023-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumpleanio',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
