# Generated by Django 4.2.3 on 2023-08-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frater', '0002_alter_cumpleanio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraternidad',
            name='banco',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='color',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='mensualidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='monto_no_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='monto_suspendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='nro_cuenta',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='fraternidad',
            name='turno_semanal',
            field=models.CharField(default='', max_length=50),
        ),
    ]
