# Generated by Django 4.2.3 on 2023-09-08 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('es_entresemana', models.BooleanField(default=False)),
                ('estado_reserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=-1)),
                ('en_curso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('dia', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(default='', null=True)),
                ('costo_entresemana', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_finsemana', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.grupoturno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('grupo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.grupoturno')),
            ],
        ),
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField(default='', max_length=700)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='DeudaExtraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('detalle', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('extraordinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.extraordinaria')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePagoMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.mensualidad')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePagoExtraordianria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda_extraordinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.deudaextraordinaria')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePagoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.pago')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendas.tipoevento'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
