# Generated by Django 4.2.3 on 2023-07-26 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.deuda')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.tipoevento')),
            ],
        ),
        migrations.AddField(
            model_name='deuda',
            name='estado_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendas.estadodeuda'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cargo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_detalle', models.DateField(auto_now_add=True)),
                ('concepto', models.CharField(default='', max_length=300)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.deuda')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField(default='', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendas.estadoreserva')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendas.tipoevento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
