# Generated by Django 4.2.3 on 2023-08-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendas', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_semana', models.IntegerField(default=0)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia_default', models.IntegerField(default=0)),
                ('dias', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.turno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
