# Generated by Django 4.2.3 on 2023-09-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_turnopl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='mensualidad',
            name='pagado',
        ),
        migrations.AddField(
            model_name='detallepagoevento',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepagoextraordianria',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepagomensualidad',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
