# Generated by Django 4.2.7 on 2024-04-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_detallepagoevento_canselado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurnoPl',
        ),
    ]
