# Generated by Django 4.2.3 on 2023-08-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_turno_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='estado_reserva',
            new_name='estado_deuda',
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dia_default',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='deuda',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deuda',
            name='deuda_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.deuda')),
            ],
        ),
        migrations.CreateModel(
            name='DeudaExtraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.deuda')),
                ('extraordinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.extraordinaria')),
            ],
        ),
    ]
