# Generated by Django 4.2.3 on 2023-09-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_rename_monto_fijo_mensualidad_costo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='nro_semana',
            new_name='dia',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='fecha_antigua',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_nueva',
        ),
        migrations.AddField(
            model_name='turno',
            name='semana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
